version: '3.3'
services:
  #Main Container
  docker4dev:
    build:
      context: .
      args:
        - PROJECT_NAME=${APP_PROJECT_NAME}
        - PROJECT_URL=${APP_PROJECT_URL}
        - PROJECT_NGINX_SERVER_NAME=${APP_PROJECT_NGINX_SERVER_NAME}
        - SSH_USER_NAME=${APP_SSH_USER_NAME}
        - SSH_USER_PASSWORD=${APP_SSH_USER_PASSWORD}
        - TZ=${APP_TZ}
      dockerfile: Dockerfile
    container_name: ${APP_PROJECT_NAME}-docker4dev
    volumes:
      - ./webroot:/var/www/${APP_PROJECT_NAME}
      - ./certs:/opt/certs
    ports:
      - "2222:22"
      - "80:80"
      - "443:443"
    environment:
      - PHP_IDE_CONFIG=serverName=${APP_PROJECT_NAME}
    links:
      - mongo:${APP_PROJECT_NAME}-mongo
    networks:
      - frontend
      - backend
    depends_on:
      - mongo
    dns:
      - 8.8.8.8
      - 8.4.4.4
    tty: true

  #Other Service
  mongo:
    container_name: ${APP_PROJECT_NAME}-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${APP_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "27017:27017"
    expose:
      - 27017
    networks:
        - frontend
        - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"
